# Generated by Django 5.0 on 2023-12-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beecost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeofsell',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/place_of_sell/'),
        ),
        migrations.AddField(
            model_name='placeofsell',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/place_of_sell/'),
        ),
    ]
