# Generated by Django 5.0 on 2023-12-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beecost', '0003_alter_product_current_price_alter_product_old_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
